dataset : COCO #  VOC, COCO
model : MNFCOS  # FCOS, HISFCOS,  MNFCOS
VOC : config/voc.yaml
COCO : config/coco.yaml
amp : True  # True False
ddp_enabled : True  #  True
persistent_workers : False
#savename : Test58
savename : COCO_Str_test8
#savename : VOC_test7
prefetch_factor : 2

