dataset : voc #  VOC, COCO
model : MNFCOS  # FCOS, HISFCOS MNFCOS
voc : config/voc.yaml
coco : config/coco.yaml
amp : True
ddp_enabled : False
persistent_workers : True
savename : Test25
prefetch_factor : 2


